spring:
  application:
    name: service-zuul

server:
  port: 8769

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      service-id: service-ribbon
    api-b:
      path: /api-b/**
      service-id: service-feign
